/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package paneles;

import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Usuario
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox = new javax.swing.JComboBox<>();
        jPanelGeneral = new javax.swing.JPanel();
        jPanelMostrarMensajes = new javax.swing.JPanel();
        jButtonInformacion = new javax.swing.JButton();
        jButtonError = new javax.swing.JButton();
        jButtonWarning = new javax.swing.JButton();
        jPanelMostrarConfirmacion = new javax.swing.JPanel();
        jButtonConfirmacion = new javax.swing.JButton();
        jButtonAbrirDialogo = new javax.swing.JButton();
        jPanelMostrarEntrada = new javax.swing.JPanel();
        jButtonBienvenido = new javax.swing.JButton();
        jButtonDesplegable = new javax.swing.JButton();
        jPanelMostrarOpciones = new javax.swing.JPanel();
        jButtonOpciones = new javax.swing.JButton();

        jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelGeneral.setBackground(new java.awt.Color(0, 102, 102));

        jPanelMostrarMensajes.setBackground(new java.awt.Color(0, 102, 102));
        jPanelMostrarMensajes.setLayout(new java.awt.GridLayout(1, 0, 20, 0));

        jButtonInformacion.setBackground(new java.awt.Color(153, 153, 0));
        jButtonInformacion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonInformacion.setForeground(new java.awt.Color(255, 255, 255));
        jButtonInformacion.setText("Informacion");
        jButtonInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInformacionActionPerformed(evt);
            }
        });
        jPanelMostrarMensajes.add(jButtonInformacion);

        jButtonError.setBackground(new java.awt.Color(153, 153, 0));
        jButtonError.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonError.setForeground(new java.awt.Color(255, 255, 255));
        jButtonError.setText("Error");
        jButtonError.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonErrorActionPerformed(evt);
            }
        });
        jPanelMostrarMensajes.add(jButtonError);

        jButtonWarning.setBackground(new java.awt.Color(153, 153, 0));
        jButtonWarning.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonWarning.setForeground(new java.awt.Color(255, 255, 255));
        jButtonWarning.setText("Warning");
        jButtonWarning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWarningActionPerformed(evt);
            }
        });
        jPanelMostrarMensajes.add(jButtonWarning);

        jPanelMostrarConfirmacion.setBackground(new java.awt.Color(0, 102, 102));
        jPanelMostrarConfirmacion.setLayout(new java.awt.GridLayout(2, 1, 0, 25));

        jButtonConfirmacion.setBackground(new java.awt.Color(153, 153, 0));
        jButtonConfirmacion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonConfirmacion.setForeground(new java.awt.Color(255, 255, 255));
        jButtonConfirmacion.setText("Confirmación");
        jButtonConfirmacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmacionActionPerformed(evt);
            }
        });
        jPanelMostrarConfirmacion.add(jButtonConfirmacion);

        jButtonAbrirDialogo.setBackground(new java.awt.Color(153, 153, 0));
        jButtonAbrirDialogo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonAbrirDialogo.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAbrirDialogo.setText("Abrir Dialogo");
        jButtonAbrirDialogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbrirDialogoActionPerformed(evt);
            }
        });
        jPanelMostrarConfirmacion.add(jButtonAbrirDialogo);

        jPanelMostrarEntrada.setBackground(new java.awt.Color(0, 102, 102));
        jPanelMostrarEntrada.setLayout(new java.awt.GridLayout(1, 0, 25, 0));

        jButtonBienvenido.setBackground(new java.awt.Color(153, 153, 0));
        jButtonBienvenido.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonBienvenido.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBienvenido.setText("Bienvenido");
        jButtonBienvenido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBienvenidoActionPerformed(evt);
            }
        });
        jPanelMostrarEntrada.add(jButtonBienvenido);

        jButtonDesplegable.setBackground(new java.awt.Color(153, 153, 0));
        jButtonDesplegable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonDesplegable.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDesplegable.setText("Desplegable");
        jButtonDesplegable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDesplegableActionPerformed(evt);
            }
        });
        jPanelMostrarEntrada.add(jButtonDesplegable);

        jPanelMostrarOpciones.setLayout(new java.awt.CardLayout());

        jButtonOpciones.setBackground(new java.awt.Color(153, 153, 0));
        jButtonOpciones.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonOpciones.setForeground(new java.awt.Color(255, 255, 255));
        jButtonOpciones.setText("Opciones");
        jButtonOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpcionesActionPerformed(evt);
            }
        });
        jPanelMostrarOpciones.add(jButtonOpciones, "card2");

        javax.swing.GroupLayout jPanelGeneralLayout = new javax.swing.GroupLayout(jPanelGeneral);
        jPanelGeneral.setLayout(jPanelGeneralLayout);
        jPanelGeneralLayout.setHorizontalGroup(
            jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeneralLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelMostrarConfirmacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelMostrarMensajes, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                    .addComponent(jPanelMostrarEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelMostrarOpciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40))
        );
        jPanelGeneralLayout.setVerticalGroup(
            jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeneralLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanelMostrarMensajes, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                .addGap(33, 33, 33)
                .addComponent(jPanelMostrarConfirmacion, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                .addGap(37, 37, 37)
                .addComponent(jPanelMostrarEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addGap(37, 37, 37)
                .addComponent(jPanelMostrarOpciones, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInformacionActionPerformed
        JOptionPane.showMessageDialog(this, "Este es el mensaje de informacion","INFORMACIÓN", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonInformacionActionPerformed

    private void jButtonErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonErrorActionPerformed
       JOptionPane.showMessageDialog(this, "Mensaje de error","ERROR", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jButtonErrorActionPerformed

    private void jButtonWarningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWarningActionPerformed
        JOptionPane.showMessageDialog(this, "Este es un mensaje de emergencia","EMERGENCIA", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jButtonWarningActionPerformed

    private void jButtonConfirmacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmacionActionPerformed
        JOptionPane.showConfirmDialog(this, "¿Quiere borrar el registro?","CONFIRMACIÓN", JOptionPane.YES_NO_CANCEL_OPTION);
    }//GEN-LAST:event_jButtonConfirmacionActionPerformed

    private void jButtonAbrirDialogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbrirDialogoActionPerformed
               int opcionElegida = JOptionPane.showConfirmDialog(this, "¿Desea abrir una nueva ventana?","CONFIRMACIÓN", JOptionPane.YES_NO_CANCEL_OPTION);
               if (opcionElegida == JOptionPane.YES_OPTION){
                    DialogoCreado dialogoCreado = new DialogoCreado(this, true);
                    dialogoCreado.setVisible(true);
                   
               }
    }//GEN-LAST:event_jButtonAbrirDialogoActionPerformed

    private void jButtonBienvenidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBienvenidoActionPerformed
        String nombre = JOptionPane.showInputDialog(this,"Indica tú nombre","BIENVENIDO" ,JOptionPane.QUESTION_MESSAGE);
        if(!nombre.isBlank()){
                JOptionPane.showMessageDialog(this,"Hola " + nombre,"BIENVENIDO", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_jButtonBienvenidoActionPerformed

    private void jButtonDesplegableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDesplegableActionPerformed
       String[] colores = { "Rojo", "Verde", "Azul" }; // puedo crear objetos sin nesecidad de que se vean en una interfaz
    JComboBox<String> comboBox = new JComboBox<>(colores);
    JLabel etiqueta = new JLabel("Elige un color: ");
      //Con el j panel le puedo meter lo que yo quiera y luego pasarlo como parametro al JOptionpal
    JPanel panel = new JPanel();
    panel.add(etiqueta);
    panel.add(comboBox); 
    
    int seleccion = JOptionPane.showConfirmDialog(this, panel, "DESPLEGABLE", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
    
    if (seleccion == JOptionPane.OK_OPTION) {
    String colorSeleccionado = (String) comboBox.getSelectedItem();
   
    JOptionPane.showMessageDialog(this, "Has seleccionado: " + colorSeleccionado);
    }
    }//GEN-LAST:event_jButtonDesplegableActionPerformed

    private void jButtonOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpcionesActionPerformed
        Object[] opciones = { "Opción 1", "Opción 2", "Opción 3" };
        int seleccion = JOptionPane.showOptionDialog(this,
                                             "Selecciona un botón", // El mensaje
                                             "OPCIONES",  // El título del diálogo
                                             JOptionPane.DEFAULT_OPTION,
                                             JOptionPane.QUESTION_MESSAGE,
                                             null,
                                             opciones,     // Aqui debo pasar el array de las opciones
                                             opciones[2]); // La opción predeterminada
        
    }//GEN-LAST:event_jButtonOpcionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAbrirDialogo;
    private javax.swing.JButton jButtonBienvenido;
    private javax.swing.JButton jButtonConfirmacion;
    private javax.swing.JButton jButtonDesplegable;
    private javax.swing.JButton jButtonError;
    private javax.swing.JButton jButtonInformacion;
    private javax.swing.JButton jButtonOpciones;
    private javax.swing.JButton jButtonWarning;
    private javax.swing.JComboBox<String> jComboBox;
    private javax.swing.JPanel jPanelGeneral;
    private javax.swing.JPanel jPanelMostrarConfirmacion;
    private javax.swing.JPanel jPanelMostrarEntrada;
    private javax.swing.JPanel jPanelMostrarMensajes;
    private javax.swing.JPanel jPanelMostrarOpciones;
    // End of variables declaration//GEN-END:variables
}
