/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package paneles;

import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelGeneral = new javax.swing.JPanel();
        jPanelMostrarMensajes = new javax.swing.JPanel();
        jButtonInformacion = new javax.swing.JButton();
        jButtonError = new javax.swing.JButton();
        jButtonWarning = new javax.swing.JButton();
        jPanelMostrarConfirmacion = new javax.swing.JPanel();
        jButtonConfirmacion = new javax.swing.JButton();
        jButtonAbrirDialogo = new javax.swing.JButton();
        jPanelMostrarEntrada = new javax.swing.JPanel();
        jButtonBienvenido = new javax.swing.JButton();
        jButtonDesplegable = new javax.swing.JButton();
        jPanelMostrarOpciones = new javax.swing.JPanel();
        jButtonOpciones = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelGeneral.setBackground(new java.awt.Color(0, 102, 102));

        jPanelMostrarMensajes.setBackground(new java.awt.Color(0, 102, 102));
        jPanelMostrarMensajes.setLayout(new java.awt.GridLayout(1, 0, 20, 0));

        jButtonInformacion.setText("Informacion");
        jButtonInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInformacionActionPerformed(evt);
            }
        });
        jPanelMostrarMensajes.add(jButtonInformacion);

        jButtonError.setText("Error");
        jPanelMostrarMensajes.add(jButtonError);

        jButtonWarning.setText("Warning");
        jPanelMostrarMensajes.add(jButtonWarning);

        jPanelMostrarConfirmacion.setBackground(new java.awt.Color(0, 102, 102));
        jPanelMostrarConfirmacion.setLayout(new java.awt.GridLayout(2, 1, 0, 25));

        jButtonConfirmacion.setText("Confirmación");
        jPanelMostrarConfirmacion.add(jButtonConfirmacion);

        jButtonAbrirDialogo.setText("Abrir Dialogo");
        jPanelMostrarConfirmacion.add(jButtonAbrirDialogo);

        jPanelMostrarEntrada.setBackground(new java.awt.Color(0, 102, 102));
        jPanelMostrarEntrada.setLayout(new java.awt.GridLayout(1, 0, 25, 0));

        jButtonBienvenido.setText("Bienvenido");
        jPanelMostrarEntrada.add(jButtonBienvenido);

        jButtonDesplegable.setText("Desplegable");
        jPanelMostrarEntrada.add(jButtonDesplegable);

        jPanelMostrarOpciones.setLayout(new java.awt.CardLayout());

        jButtonOpciones.setText("Opciones");
        jPanelMostrarOpciones.add(jButtonOpciones, "card2");

        javax.swing.GroupLayout jPanelGeneralLayout = new javax.swing.GroupLayout(jPanelGeneral);
        jPanelGeneral.setLayout(jPanelGeneralLayout);
        jPanelGeneralLayout.setHorizontalGroup(
            jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeneralLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelMostrarConfirmacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelMostrarMensajes, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                    .addComponent(jPanelMostrarEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelMostrarOpciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40))
        );
        jPanelGeneralLayout.setVerticalGroup(
            jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeneralLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanelMostrarMensajes, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                .addGap(33, 33, 33)
                .addComponent(jPanelMostrarConfirmacion, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                .addGap(37, 37, 37)
                .addComponent(jPanelMostrarEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addGap(37, 37, 37)
                .addComponent(jPanelMostrarOpciones, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInformacionActionPerformed
        JOptionPane.showMessageDialog(this, "Este es el mensaje de informacion","Informacion", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonInformacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAbrirDialogo;
    private javax.swing.JButton jButtonBienvenido;
    private javax.swing.JButton jButtonConfirmacion;
    private javax.swing.JButton jButtonDesplegable;
    private javax.swing.JButton jButtonError;
    private javax.swing.JButton jButtonInformacion;
    private javax.swing.JButton jButtonOpciones;
    private javax.swing.JButton jButtonWarning;
    private javax.swing.JPanel jPanelGeneral;
    private javax.swing.JPanel jPanelMostrarConfirmacion;
    private javax.swing.JPanel jPanelMostrarEntrada;
    private javax.swing.JPanel jPanelMostrarMensajes;
    private javax.swing.JPanel jPanelMostrarOpciones;
    // End of variables declaration//GEN-END:variables
}
