// default package
// Generated 15 ene 2024 17:10:56 by Hibernate Tools 6.3.1.Final
package entidades;

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Educacion generated by hbm2java
 */
public class Educacion implements java.io.Serializable {

	private int edId;
	private Investigador investigador;
	private Integer uniId;
	private String edGrado;
	private String edCampo;
	private String edDescripcion;

	public Educacion() {
	}

	public Educacion(int edId, Investigador investigador, Integer uniId, String edGrado, String edCampo,
			String edDescripcion) {
		this.edId = edId;
		this.investigador = investigador;
		this.uniId = uniId;
		this.edGrado = edGrado;
		this.edCampo = edCampo;
		this.edDescripcion = edDescripcion;
	}

	public int getEdId() {
		return this.edId;
	}

	public void setEdId(int edId) {
		this.edId = edId;
	}

	public Investigador getInvestigador() {
		return this.investigador;
	}

	public void setInvestigador(Investigador investigador) {
		this.investigador = investigador;
	}

	public Integer getUniId() {
		return this.uniId;
	}

	public void setUniId(Integer uniId) {
		this.uniId = uniId;
	}

	public String getEdGrado() {
		return this.edGrado;
	}

	public void setEdGrado(String edGrado) {
		this.edGrado = edGrado;
	}

	public String getEdCampo() {
		return this.edCampo;
	}

	public void setEdCampo(String edCampo) {
		this.edCampo = edCampo;
	}

	public String getEdDescripcion() {
		return this.edDescripcion;
	}

	public void setEdDescripcion(String edDescripcion) {
		this.edDescripcion = edDescripcion;
	}

}
