/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package actividad_6_eltonsaravia;
import javax.swing.JFrame;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;
/**
 *
 * @author Usuario
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        jButtonDiagrama.addActionListener(evt -> dibujarDiagrama());
    }

    private void dibujarDiagrama() {
        DefaultPieDataset dataset = new DefaultPieDataset();
        dataset.setValue("Categoría 1", 43.2);
        dataset.setValue("Categoría 2", 27.9);
        dataset.setValue("Categoría 3", 79.5);

        JFreeChart chart = ChartFactory.createPieChart(
            "Gráfico de Pastel",   // título del gráfico
            dataset,               // dataset
            true,                  // incluir leyendas
            true,
            false);

        ChartPanel chartPanel = new ChartPanel(chart);
        jPanelGrafica.removeAll(); // Eliminar componentes previos
        jPanelGrafica.add(chartPanel);
        jPanelGrafica.updateUI(); // Actualizar el UI para mostrar el nuevo gráfico
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonDiagrama = new javax.swing.JButton();
        jButtonDiagrama3D = new javax.swing.JButton();
        jButtonDiagramaCircular = new javax.swing.JButton();
        jButtonDiagramaBarras = new javax.swing.JButton();
        jButtonDiagramaLineas = new javax.swing.JButton();
        jButtonDiagramaCascada = new javax.swing.JButton();
        jPanelGrafica = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonDiagrama.setBackground(new java.awt.Color(0, 102, 102));
        jButtonDiagrama.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonDiagrama.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDiagrama.setText("Diagrama");

        jButtonDiagrama3D.setBackground(new java.awt.Color(0, 102, 102));
        jButtonDiagrama3D.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonDiagrama3D.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDiagrama3D.setText("Diagrama3D");

        jButtonDiagramaCircular.setBackground(new java.awt.Color(0, 102, 102));
        jButtonDiagramaCircular.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonDiagramaCircular.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDiagramaCircular.setText("Diagrama Circular");

        jButtonDiagramaBarras.setBackground(new java.awt.Color(0, 102, 102));
        jButtonDiagramaBarras.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonDiagramaBarras.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDiagramaBarras.setText("Diagrama Barras");

        jButtonDiagramaLineas.setBackground(new java.awt.Color(0, 102, 102));
        jButtonDiagramaLineas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonDiagramaLineas.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDiagramaLineas.setText("DiagramaLineas");

        jButtonDiagramaCascada.setBackground(new java.awt.Color(0, 102, 102));
        jButtonDiagramaCascada.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonDiagramaCascada.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDiagramaCascada.setText("Diagrama Cascada");

        javax.swing.GroupLayout jPanelGraficaLayout = new javax.swing.GroupLayout(jPanelGrafica);
        jPanelGrafica.setLayout(jPanelGraficaLayout);
        jPanelGraficaLayout.setHorizontalGroup(
            jPanelGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 268, Short.MAX_VALUE)
        );
        jPanelGraficaLayout.setVerticalGroup(
            jPanelGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonDiagramaCascada)
                    .addComponent(jButtonDiagramaLineas)
                    .addComponent(jButtonDiagramaCircular)
                    .addComponent(jButtonDiagrama)
                    .addComponent(jButtonDiagrama3D)
                    .addComponent(jButtonDiagramaBarras))
                .addGap(52, 52, 52)
                .addComponent(jPanelGrafica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelGrafica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButtonDiagrama)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDiagrama3D)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDiagramaCircular)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDiagramaBarras)
                        .addGap(20, 20, 20)
                        .addComponent(jButtonDiagramaLineas)
                        .addGap(33, 33, 33)
                        .addComponent(jButtonDiagramaCascada)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() { 
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDiagrama;
    private javax.swing.JButton jButtonDiagrama3D;
    private javax.swing.JButton jButtonDiagramaBarras;
    private javax.swing.JButton jButtonDiagramaCascada;
    private javax.swing.JButton jButtonDiagramaCircular;
    private javax.swing.JButton jButtonDiagramaLineas;
    private javax.swing.JPanel jPanelGrafica;
    // End of variables declaration//GEN-END:variables
}
