// default package
// Generated 22 ene 2024, 6:41:16 by Hibernate Tools 6.3.1.Final
package tables;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * Proyectos generated by hbm2java
 */

@Entity
@Table(name="proyectos")
public class Proyectos implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name="PROYECTO_ID")
	private Integer proyectoId;
    @ManyToOne
    @JoinColumn(name = "INV_ID")
	private Investigador investigador;
    @Column(name="PROYECTO_NOMBRE")
	private String proyectoNombre;
    @Column(name="PROYECTO_YEAR_PUB")
	private Integer proyectoYearPub;
    @Column(name="PROYECTO_MONTO")
	private String proyectoMonto;

	public Proyectos() {
	}

	public Proyectos(Investigador investigador, String proyectoNombre, Integer proyectoYearPub, String proyectoMonto) {
		this.investigador = investigador;
		this.proyectoNombre = proyectoNombre;
		this.proyectoYearPub = proyectoYearPub;
		this.proyectoMonto = proyectoMonto;
	}

	public Integer getProyectoId() {
		return this.proyectoId;
	}

	public void setProyectoId(Integer proyectoId) {
		this.proyectoId = proyectoId;
	}

	public Investigador getInvestigador() {
		return this.investigador;
	}

	public void setInvestigador(Investigador investigador) {
		this.investigador = investigador;
	}

	public String getProyectoNombre() {
		return this.proyectoNombre;
	}

	public void setProyectoNombre(String proyectoNombre) {
		this.proyectoNombre = proyectoNombre;
	}

	public Integer getProyectoYearPub() {
		return this.proyectoYearPub;
	}

	public void setProyectoYearPub(Integer proyectoYearPub) {
		this.proyectoYearPub = proyectoYearPub;
	}

	public String getProyectoMonto() {
		return this.proyectoMonto;
	}

	public void setProyectoMonto(String proyectoMonto) {
		this.proyectoMonto = proyectoMonto;
	}

}
