CREATE OR REPLACE TYPE TIPO_PERSONA AS OBJECT(
  -- EJEMPLO DE COMO FUNCIONA EL POLIMORFISMO DE METODOS COAN HERENCIA
    DNIE VARCHAR (10),
    NOMBRE VARCHAR2(25),
    FEC_NAC DATE,
    MEMBER FUNCTION EDAD RETURN NUMBER,
    FINAL MEMBER FUNCTION GET_DNI RETURN VARCHAR2,
    MEMBER FUNCTION GET_NOMBRE RETURN VARCHAR2,
    MEMBER PROCEDURE VER_DATOS
) NOT FINAL;




CREATE OR REPLACE TYPE BODY TIPO_PERSONA AS  -- PARA OBTENER LA FECHA
    MEMBER FUNCTION EDAD RETURN NUMBER IS ED NUMBER;
    BEGIN
        ED := TO_CHAR(SYSDATE, 'YYYY') - TO_CHAR(FEC_NAC,'YYYY');
        RETURN ED;
    END;
    
    
    FINAL MEMBER FUNCTION GET_DNI RETURN VARCHAR2 IS
    BEGIN
        RETURN DNI;
    END;
    
        FINAL MEMBER FUNCTION GET_NOMBRE RETURN VARCHAR2 IS
    BEGIN
        RETURN NOMBRE;
    END;
    
    MEMBER PROCEDURE VER_DATOS IS 
    BEGIN
        DBMS_OUTPU.put_line(NOMBRE || 'tiene' || EDAD || 'años' );
    END;    
END;

 CREATE OR REPLACE TYPE TIPO_ALUMNO UNDER TIPO_PERSONA(
    CURSO VARCHAR2(10),
    NOTA_FINAL NUMBER,
    MEMBER FUNCTION NOTA RETURN NUMBER,
    OVERRIDING MEMBER PROCEDURE VER_DATOS
 );
 
 
 CREATE OR REPLACE TYPE BODY TIPO_ALUMNO AS  -- PARA OBTENER LA FECHA
    MEMBER FUNCTION NOTA RETURN NUMBER AS
    BEGIN
        RETURN NOTA;
    END;
    OVERRIDING MEMBER PROCEDURE VER_DATOS AS
    BEGIN
        DBMS_OUTPU.put_line(CURSO || ' ' || NOTA_FINAL );
    END;
END;



    